apiVersion: v1
kind: Service
metadata:
  name: demo-apis-service
spec:
  selector:
    app: demo-apis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000
  type: NodePort